<a href="https://colab.research.google.com/github/malakmlk/ML/blob/main/TP_FAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


---
# **Saiem MALAK SIQ2**
---
TP FAS 



# **Chargement des bibliothèques**



In [ ]:
import os
import matplotlib.pyplot as plt
import tensorflow as tf

# **Le problem de classification des fleures d'iris:**
Comme dataset je vais utiliser le jeu de données [IRIS](https://storage.googleapis.com/download.tensorflow.org/data/iris_training.csv). Ce dernier est une base de données regroupant les caractéristiques de trois espèces de fleurs d’Iris, à savoir Setosa, Versicolour et Virginica. Chaque ligne de ce jeu de données est une observation des caractéristiques d’une fleur d’Iris. Ce dataset décrit les espèces d’Iris par quatre propriétés : longueur et largeur de sépales ainsi que longueur et largeur de pétales. La base de données comporte 120 observations .

# **Chargement du jeu de données IRIS**
Dans cette partie je vais télecharger le dataset file et le convertir en une structure qu'on peut utiliser dans un programme python.
Pour réaliser cela on utiliser la methode **tf.keras.utils.get_file**.
je vais Téléchargez le fichier texte CSV et analysez ces valeurs, puis mélangez-le un peu.

In [ ]:
train_dataset_url="https://storage.googleapis.com/download.tensorflow.org/data/iris_training.csv"
train_dataset_fp = tf.keras.utils.get_file(fname=os.path.basename(train_dataset_url),
                                           origin=train_dataset_url)

print("Local copy of the dataset file: {}".format(train_dataset_fp))

Local copy of the dataset file: /root/.keras/datasets/iris_training.csv


# **Visualisation du jeu de données**

En utilisant la commande head -n10,on peut visualiser les 10 premiers lignes.

In [ ]:
!head -n10 {train_dataset_fp}

120,4,setosa,versicolor,virginica
6.4,2.8,5.6,2.2,2
5.0,2.3,3.3,1.0,1
4.9,2.5,4.5,1.7,2
4.9,3.1,1.5,0.1,0
5.7,3.8,1.7,0.3,0
4.4,3.2,1.3,0.2,0
5.4,3.4,1.5,0.4,0
6.9,3.1,5.1,2.3,2
6.7,3.1,4.4,1.4,1


À partir de cette vue de l'ensemble de données, on peut conclure que:

1. La première ligne est un en-tête contenant des informations sur l'ensemble   de données:
Il y a 120 exemples au total. Chaque exemple a quatre feautures et l'un des trois noms d'étiquettes possibles.
2. Les lignes suivantes sont des enregistrements de données, un exemple par ligne, où:
Les quatre premiers champs sont des **features** : ce sont les caractéristiques d'un exemple. Ici, les champs contiennent des nombres flottants représentant les mesures des fleurs.
La dernière colonne est le **label** : c'est la valeur que nous voulons prédire. Pour cet ensemble de données, il s'agit d'une valeur entière de 0, 1 ou 2 qui correspond à un nom de fleur.

In [ ]:
column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

feature_names = column_names[:-1]
label_name = column_names[-1]

print("Features: {}".format(feature_names))
print("Label: {}".format(label_name))

Features: ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
Label: species


In [ ]:
class_names = ['Iris setosa', 'Iris versicolor', 'Iris virginica']

# **Création d'un tf.data.dataset**

 Afin de pouvoir faire l'analyse de ces données dans une format approprié je vais travailler avec la fonction **tf.data.experimental.make_csv_dataset** qui retourne  un tf.data.Dataset de tf.data.Dataset (features, label) , où features est un dictionnaire: {'feature_name': value}.

In [ ]:
batch_size = 120

train_dataset = tf.data.experimental.make_csv_dataset(
    train_dataset_fp,
    batch_size,
    column_names=column_names,
    label_name=label_name,
    num_epochs=1)

In [ ]:
features, labels = next(iter(train_dataset))

print(features)

OrderedDict([('sepal_length', <tf.Tensor: shape=(120,), dtype=float32, numpy=
array([4.6, 5.6, 5.8, 6.8, 4.6, 4.9, 7.2, 5.4, 6. , 6.4, 5. , 5.8, 5.2,
       5. , 6.1, 5.9, 6.7, 6.8, 6.4, 7.2, 5.5, 6.7, 7. , 4.9, 5.5, 7.7,
       6.3, 7.2, 5.4, 5.2, 4.9, 6. , 6.8, 6.3, 5.1, 6.3, 7.9, 4.8, 6.4,
       6.3, 4.7, 5. , 5.4, 5.8, 7.7, 7.7, 6.5, 5. , 5. , 4.4, 5.7, 6. ,
       6.1, 5.8, 6.4, 6.5, 6.3, 6.5, 4.9, 4.7, 6.6, 5.1, 6.9, 5.8, 6.7,
       6.5, 4.8, 5. , 6.2, 5. , 4.6, 4.6, 5.8, 5. , 7.7, 5.1, 6.1, 5.7,
       5.7, 6.9, 7.6, 6.4, 4.8, 4.8, 4.5, 6.2, 7.3, 5.7, 4.4, 4.4, 6.6,
       4.9, 6.7, 5.7, 5.1, 6.1, 5.3, 6.9, 6.5, 6.7, 5.2, 5.4, 5.1, 5.7,
       6. , 4.9, 6.1, 5.5, 6.3, 5.6, 5.4, 5.9, 6.4, 6.2, 5. , 5.6, 5. ,
       5.5, 5.1, 7.4], dtype=float32)>), ('sepal_width', <tf.Tensor: shape=(120,), dtype=float32, numpy=
array([3.1, 2.9, 2.8, 2.8, 3.4, 3.1, 3.6, 3.4, 2.9, 3.2, 2.3, 2.6, 3.4,
       3.5, 2.8, 3. , 3.1, 3. , 3.2, 3. , 2.4, 3. , 3.2, 2.5, 3.5, 2.8,
       2.7, 3.2, 3.9, 2.7

la fonction pack_features_vector va rendre le dictionaire des features en une seule array liste de shape(120,4).

In [ ]:
def pack_features_vector(features, labels):
  """Pack the features into a single array."""
  features = tf.stack(list(features.values()), axis=1)
  return features, labels

In [ ]:
train_dataset = train_dataset.map(pack_features_vector)
features, labels = next(iter(train_dataset))
print(labels[:10])

tf.Tensor([0 1 2 1 2 1 0 0 1 1], shape=(10,), dtype=int32)


# **Le choix du modèle**
le modele va comporter **3 couche**,deux couches avec 10 noeud et une chouche de sortie avec trois noeud, et comme fonction d'activation j'ai choisi de travailler avec la donction **RELU**

In [ ]:
model = tf.keras.Sequential([
  tf.keras.layers.Dense(10, activation=tf.nn.relu, input_shape=(4,)),  # input shape required
  tf.keras.layers.Dense(10, activation=tf.nn.relu),
  tf.keras.layers.Dense(3)
])

# **Training du modèle**

## Définition de loss et gradiant 

In [ ]:
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
def loss(model, x, y, training):
 
  y_ = model(x, training=training)

  return loss_object(y_true=y, y_pred=y_)


l = loss(model, features, labels, training=False)
print("Loss test: {}".format(l))

Loss test: 1.4662072658538818


In [ ]:
def grad(model, inputs, targets):
  with tf.GradientTape() as tape:
    loss_value = loss(model, inputs, targets, training=True)
  return loss_value, tape.gradient(loss_value, model.trainable_variables)

## Créer un optimiseur

In [ ]:
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)


In [ ]:
loss_value, grads = grad(model, features, labels)

print("Step: {}, Initial Loss: {}".format(optimizer.iterations.numpy(),
                                          loss_value.numpy()))

optimizer.apply_gradients(zip(grads, model.trainable_variables))

print("Step: {},         Loss: {}".format(optimizer.iterations.numpy(),
                                          loss(model, features, labels, training=True).numpy()))

Step: 0, Initial Loss: 1.4662072658538818
Step: 1,         Loss: 1.3233238458633423


## Boucle d'entraînement

In [ ]:

train_loss_results = []
train_accuracy_results = []

num_epochs = 650

for epoch in range(num_epochs):
  epoch_loss_avg = tf.keras.metrics.Mean()
  epoch_accuracy = tf.keras.metrics.SparseCategoricalAccuracy()

  
  for x, y in train_dataset:
    # Optimizer le modele
    loss_value, grads = grad(model, x, y)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))

    # Track progress
    epoch_loss_avg.update_state(loss_value)  # ajouter le loss courant
    # comparaison entre le label prédictée et le label réel
  
    epoch_accuracy.update_state(y, model(x, training=True))

  # End epoch
  train_loss_results.append(epoch_loss_avg.result())
  train_accuracy_results.append(epoch_accuracy.result())

  if epoch % 50 == 0:
    print("Epoch {:03d}: Loss: {:.3f}, Accuracy: {:.3%}".format(epoch,
                                                                epoch_loss_avg.result(),
                                                                epoch_accuracy.result()))

Epoch 000: Loss: 1.323, Accuracy: 35.000%
Epoch 050: Loss: 0.794, Accuracy: 69.167%
Epoch 100: Loss: 0.701, Accuracy: 75.000%
Epoch 150: Loss: 0.563, Accuracy: 86.667%
Epoch 200: Loss: 0.461, Accuracy: 87.500%
Epoch 250: Loss: 0.394, Accuracy: 90.000%
Epoch 300: Loss: 0.346, Accuracy: 92.500%
Epoch 350: Loss: 0.303, Accuracy: 95.000%
Epoch 400: Loss: 0.265, Accuracy: 95.833%
Epoch 450: Loss: 0.233, Accuracy: 96.667%
Epoch 500: Loss: 0.209, Accuracy: 97.500%
Epoch 550: Loss: 0.189, Accuracy: 97.500%
Epoch 600: Loss: 0.173, Accuracy: 97.500%


# **Tester le modèle**

Pour évaluer l'efficacité d'un modèle, les exemples utilisés sont différents que des exemples utilisés pour entraîner le modèle.

La configuration de l'ensemble de Dataset test est similaire à la configuration de l'ensemble de Dataset entraînement. Téléchargez le fichier texte CSV et analysez ces valeurs, puis mélangez-le un peu:

In [ ]:
test_url = "https://storage.googleapis.com/download.tensorflow.org/data/iris_test.csv"

test_fp = tf.keras.utils.get_file(fname=os.path.basename(test_url),
                                  origin=test_url)

In [ ]:
test_dataset = tf.data.experimental.make_csv_dataset(
    test_fp,
    batch_size,
    column_names=column_names,
    label_name='species',
    num_epochs=1,
    shuffle=False)

test_dataset = test_dataset.map(pack_features_vector)

In [ ]:
test_accuracy = tf.keras.metrics.Accuracy()

for (x, y) in test_dataset:
  
  logits = model(x, training=False)
  prediction = tf.argmax(logits, axis=1, output_type=tf.int32)
  test_accuracy(prediction, y)

print("Test set accuracy: {:.3%}".format(test_accuracy.result()))

Test set accuracy: 93.333%


Visualiser les valeur prédictées par rapport aux valeurs originals.

In [ ]:
tf.stack([y,prediction],axis=1)

<tf.Tensor: shape=(30, 2), dtype=int32, numpy=
array([[1, 1],
       [2, 2],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [2, 2],
       [1, 1],
       [2, 2],
       [2, 2],
       [0, 0],
       [2, 2],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [2, 2],
       [0, 0],
       [1, 2],
       [2, 2],
       [1, 2],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [2, 2],
       [1, 1]], dtype=int32)>

on peut conclure que la majorité des valeurs prédictées sont correcte.

# **Utilisation de modele**
Apres avoir tester le modele , on peut dire qu'il bon,maintenat c'est le temps de l'utiliser pour predicter des nouvelles prédictions sur d'autres examples.

In [ ]:
predict_dataset = tf.convert_to_tensor([
    [4.8,3,1.4,0.3,],#setosa
    [7,3.2,4.7,1.4],#versicolor
    [6.3,2.5,5,1.9],#virginica
    [5.9,3,5.1,1.8],#virginica
    [5,3.3,1.4,0.2]#sesota
])


predictions = model(predict_dataset, training=False)

for i, logits in enumerate(predictions):
  class_idx = tf.argmax(logits).numpy()
  p = tf.nn.softmax(logits)[class_idx]
  name = class_names[class_idx]
  print("Example {} prediction: {} ({:4.1f}%)".format(i, name, 100*p))

Example 0 prediction: Iris setosa (97.5%)
Example 1 prediction: Iris versicolor (94.7%)
Example 2 prediction: Iris virginica (76.9%)
Example 3 prediction: Iris virginica (88.3%)
Example 4 prediction: Iris setosa (98.7%)
